:PROPERTIES:
:ID:       8f82c351-8a47-4056-8032-aaa750b1983a
:END:
#+title: Getting Started With React Native

* Setting up the development environment

This page will help you install and build your first React Native app.

*If you are new to mobile development*, the easiest way to get started is with [[id:231a2988-5b9b-43ca-8531-dbf490b85ad5][Expo Go]]. Expo is a set of tools and services built around React Native and, while it has many features, the most relevant feature for us right now is that it can get you writing a React Native app within minutes. You will only need a recent version of Node.js and a phone or emulator. If you'd like to try out React Native directly in your web browser before installing any tools, you can try out [[https://snack.expo.dev/][Snack]].

*If you are already familiar with mobile development*, you may want to use React Native CLI. It requires Xcode or Android Studio to get started. If you are already have one of these tools installed, you should be able to get up and running within a few minutes. If they are not installed, you should expect to spend about an hour installing and configuring them.

** Expo Go Quickstart

Run the following command to create a new React Native project called "AwesomeProject":

#+begin_src sh

  npx create-expo-app AwesomeProject
  cd AwesomeProject
  npx expo start

#+end_src

This will start a development server for you.

*** Running your React Native application

Install the =Expo Go= app on your iOS or Android phone and connect to the same wireless network as your computer. On Android, use the Expo Go app to scan the QR code from your terminal to open your project. On iOS, use the built-in QR code scanner of the default iOS Camera app.

*** Modifying your app

Now that you have successfully run the app, let's modify it. Open *App.tsx* in your text editor of choice and edit some lines. The application should reload automatically once you save your changes.

*** That's it!

Congratulations! You've successfully run and modified your first React Native app.
