:PROPERTIES:
:ID:       2c553e84-f6f4-401b-8a7b-34df801d8698
:END:
#+title: Learn the Basics of React Native

* https://reactnative.dev/docs/tutorial
* Learn the Basics

React Native is like React, but it uses native components instead of web components as building blocks. So to understand the basic structure of a React Native app, you need to understand some of the basic React concepts, like JSX, components, =state=, and =props=. If you already know React, you still need to learn some React Native specific stuff, like the native components. This tutorial is aimed to all audiences, whether you have React experience or not.

** Hello World

In accordance with the ancient traditions of our people, we must first build an app that does nothing except say "Hello, world!". Here it is:

#+begin_src js

  import React from 'react';
  import { Text, View } from 'react-native';

  const HelloWorldApp = () => {
      return (
          <View
              style={{
                  flex: 1,
                  justifyContent: 'center',
                  alignItems: 'center',
              }}>
              <Text>Hello, world!</Text>
          </View>
      );
  };
  export default HelloWorldApp;

#+end_src

** Components

So this code is defining =HelloWorldApp=, a new =Component=. When you're building a React Native app, you'll be making new components a lot. Anything you see on the screen is some sort of component.

** Props

Most components can be customized when they are created, with different parameters. These creation parameters are called props.

Your own components can also use =props=. This lets you make a single component that is used in many different places in your app, with slightly different properties in each place. Refer to =props.YOUR_PROP_NAME= in your functional components or =this.props.YOUR_PROP_NAME= in your class components. Here's an example:

#+begin_src js

  import React from 'react';
  import {Text, View, StyleSheet} from 'react-native';

  const styles = StyleSheet.create({
    center: {
      alignItems: 'center',
    },
  });

  const Greeting = props => {
    return (
      <View style={styles.center}>
        <Text>Hello {props.name}!</Text>
      </View>
    );
  };

  const LotsOfGreetings = () => {
    return (
      <View style={[styles.center, {top: 50}]}>
        <Greeting name="Rexxar" />
        <Greeting name="Jaina" />
        <Greeting name="Valeera" />
      </View>
    );
  };

  export default LotsOfGreetings;

#+end_src

Using =name= as a prop lets us customize the =Greeting= component, so we can reuse that component for each of our greetings. This example also uses the =Greeting= component in JSX. The power to do this is what makes React so cool.

** State

Unlike props =that are read-only= and should not be modified, the =state= allows React components to change their output over time in response to user actions, network responses and anything else.

*What's the difference between state and props in React?*

In a React component, the props are the variables that we pass from a parent component to a child component. Similarly, the state are also variables, with the difference that they are not passed as parameters, but rather that the component initializes and manages them internally.

*Are there difference between React and React Native to handle the state?*

#+begin_src js

  // ReactJS Counter Example using Hooks!

  import React, {useState} from 'react';

  const App = () => {
    const [count, setCount] = useState(0);

    return (
      <div className="container">
        <p>You clicked {count} times</p>
        <button
          onClick={() => setCount(count + 1)}>
          Click me!
        </button>
      </div>
    );
  };


  // CSS
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
  }

#+end_src

#+begin_src js

  // React Native Counter Example using Hooks!

  import React, {useState} from 'react';
  import {View, Text, Button, StyleSheet} from 'react-native';

  const App = () => {
    const [count, setCount] = useState(0);

    return (
      <View style={styles.container}>
        <Text>You clicked {count} times</Text>
        <Button
          onPress={() => setCount(count + 1)}
          title="Click me!"
        />
      </View>
    );
  };

  // React Native Styles
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
  });

#+end_src

As shown above, there is no difference in handling the =state= between _React_ and =React Native=. You can use the state of your components both in classes and in functional components using _hooks_!

In the following example we will show the same above counter example using classes.

#+begin_src js

  import React, {Component} from 'react';
  import {StyleSheet, TouchableOpacity, Text, View} from 'react-native';

  class App extends Component {
    state = {
      count: 0,
    };

    onPress = () => {
      this.setState({
        count: this.state.count + 1,
      });
    };

    render() {
      return (
        <View style={styles.container}>
          <TouchableOpacity style={styles.button} onPress={this.onPress}>
            <Text>Click me</Text>
          </TouchableOpacity>
          <View>
            <Text>You clicked {this.state.count} times</Text>
          </View>
        </View>
      );
    }
  }

  const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    button: {
      alignItems: 'center',
      backgroundColor: '#DDDDDD',
      padding: 10,
      marginBottom: 10,
    },
  });

  export default App;

#+end_src
