#+title: React Native Tutorial

* Overview

React Native lets you build mobile apps using only JavaScript. It uses the same design as React, letting you compose a rich mobile UI from declarative components. With React Native, you don't build a mobile web app, an HTML5 app, or a hybrid app; you build a real mobile app that's indistinguishable from an app built using Objective-C or Java. React Native uses the same fundamental UI building blocks as regular iOS and Android apps. You just put those building blocks together using JavaScript and React.

** React Native Features

Following are the features of React Native:

- *React* - This is a Framework for building web and mobile apps using JavaScript.
- *Native* - You can use native components controlled by JavaScript.
- *Platforms* - React Native supports IOS and Android platform.

** React Native Advantages

Following are the advantages of React Native:

- *JavaScript* - You can use the existing JavaScript knowledge to build native mobile apps.
- *Code sharing* - You can share most of your code on different platforms.
- *Community* - The community around React and React Native is large, and you will be able to find any answer you need.

** React Native Limitations

Following are the limitations of React Native:

- *Native Components* - If you want to create native functionality which is not created yet, you will need to write some platform specific code.

* Environment Setup

There are a couple of things you need to install to set up the environment for React Native. We will use OSX as our building platform.

| Software       |
|----------------|
| NodeJS and NPM |
