#+title: Getting Started with TanStack Query

* Getting Started
** Overview

TanStack Query (FKA React Query) is often described as the missing data-fetching library for web applications, but in more technical terms, it makes *fetching, caching, synchronizing and updating server state* in your web applications a breeze.

** Motivation

Most core web frameworks *do not* come with an opinionated way of fetching or updating data in a holistic way. Because of this developers end up building either meta-frameworks which encapsulate strict opinions about data-fetching, or they invent their own ways of fetching data. This usually means cobbling together component-based state and side-effects, or using more general purpose state management libraries to store and provide asynchronous data throughout their apps.

While most traditional state management libraries are great for working with client state, they are *not so great at working with async or server state*. This is because *server state is totally different*. For starters, server state:

- Is persisted remotely in a location you do not control or own
- Requires asynchronous APIs for fetching and updating
- Implies shared ownership and can be changed by other people without your knowledge
- Can potentially become "out of date" in your applications if you're not careful

Once you grasp the nature of server state in your application, *even more challenges will arise* as you go, for example:

- Caching... (possibly the hardest thing to do in programming)
- Deduping multiple requests for the same data into a single request
- Updating "out of date" data in the background
- Knowing when data is "out of date"
- Reflecting updates to data as quickly as possible
- Performance optimizations like pagination and lazy loading data
- Managing memory and garbage collection of server state
- Memoizing query results with structural sharing

If you're not overwhelmed by that list, then that must mean that you've probably solved all of your server state problems already and deserve an award. However, if you are like a vast majority of people, you either have yet to tackle all or most of these challenges and we're only scratching the surface!

React Query is hands down one of the /best libraries/ for managing server state. It works amazingly well *out-of-the-box, with zero-config, and can be customized* to your liking as your application grows.

React Query allows you to defeat and overcome the tricky challenges and hurdles of /server state/ and control your app before it starts to control you.

On a more technical note, React Query will likely:

- Help you remove *many* lines of complicated and misunderstood code from your application and replace with just a handful of lines of React Query logic.
- Make your application more maintainable and easier to build new features without worrying about wiring up new server state data sources
- Have a direct impact on your end-users by making your application feel faster and more responsive that ever before.
- Potentially help you save on bandwidth and increase memory performance

* Installation
** NPM

#+begin_src sh

  npm i @tanstack/react-query
  # or
  pnpm add @tanstack/react-query
  # or
  yarn add @tanstack/react-query

#+end_src

React Query is compatible with React v16.8+ and works with ReactDOM and React Native.

** CDN

If you're not using a module bundler or package manager we also have a global ("UMD") build hosted on the [[https://unpkg.com]] CDN. Simply add the following =<script>= tag to the bottom of your HTML file:

#+begin_src html

  <script src="https://unpkg.com/@tanstack/react-query@4/build/umd/index.production.js"></script>

#+end_src

Once you've added this you will have access to the =window.ReactQuery= object and its exports.

* QueryWrapper.tsx

Create a file =QueryWrapper.tsx= and paste the following:

#+begin_src typescript

  'use client'

  import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
  import { ReactNode } from 'react'

  interface Props {
    children?: ReactNode
  }

  const queryClient = new QueryClient()
  const QueryWrapper = ({ children }: Props) => <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>

  export default QueryWrapper

#+end_src

Once it is done, go to your =layout.tsx= and import the *QueryWrapper*.

#+begin_src typescript

  import QueryWrapper from '../components/QueryWrapper'

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>
          <QueryWrapper>
            {children}
          </QueryWrapper>
        </body>
      </html>
    )
  }

#+end_src

*NOTE*: For some reasons if you are using *useMutation* on your project, don't forget to install =axios=.

#+begin_src sh

  yarn add axios

#+end_src
